const appname = "e-Mart";
const appversion = "Version 1.0.0";
const credits = "@RBajra";

const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "* * * * * *";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Rohit Bajra";
const forgetPass = "Forget Password?";
const login = "Login";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Login With";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";
