// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfGbha24e4vqaYUX1aj3AbJUGEYZR4klM',
    appId: '1:526267361991:web:f7b072fe65385cea7f2ce2',
    messagingSenderId: '526267361991',
    projectId: 'emart-b30ae',
    authDomain: 'emart-b30ae.firebaseapp.com',
    storageBucket: 'emart-b30ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA44kZQTZNzRWfv4m7uA7qPkz49E_BSFBE',
    appId: '1:526267361991:android:283a13dfc29c63197f2ce2',
    messagingSenderId: '526267361991',
    projectId: 'emart-b30ae',
    storageBucket: 'emart-b30ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYE7_TzixGQ8oO-_mVl6_L77cyd83GsI',
    appId: '1:526267361991:ios:2548ec0fa7c2e90a7f2ce2',
    messagingSenderId: '526267361991',
    projectId: 'emart-b30ae',
    storageBucket: 'emart-b30ae.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTYE7_TzixGQ8oO-_mVl6_L77cyd83GsI',
    appId: '1:526267361991:ios:6ba8fbe73238b67e7f2ce2',
    messagingSenderId: '526267361991',
    projectId: 'emart-b30ae',
    storageBucket: 'emart-b30ae.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
